spring:
  ## Oauth2 Security
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 542941100377-rktqhqpujilfkpo3l4jb6js8khm254d2.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - openid
  ## PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/device-inventory-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  ## JPA, Hibernate
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate.ddl-auto: update

## Flyway
flyway:
  user: admin
  password: admin
  schemas: app-db
  url: jdbc:postgresql://localhost:5432/device-inventory-db
  locations: filesystem:db/migration