version: "3"

services:
  device-inventory:
    build:
      context: ../../
      dockerfile: ./ops-tools/docker/images/device-inventory/Dockerfile
    volumes:
      - ../../:/device-inventory
    networks:
      - di-net
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/device-inventory-db?currentSchema=di_db
    depends_on:
      - postgres

  postgres:
    image: "postgres:14.1-alpine"
    restart: always
    networks:
      - di-net
    ports:
      - "8765:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: device-inventory-db
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data

networks:
  di-net:
    driver: bridge